using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace UniOpenCLI.Editor
{
    /// <summary>
    /// Generates one <c>[MenuItem]</c> method per configured command.
    /// </summary>
    /// <remarks>
    /// <c>[MenuItem]</c> is resolved at compile time, so menu entries cannot be built from
    /// the command list at runtime. The generated file is written into the consumer
    /// project (not the package folder) because UPM installs are immutable.
    /// </remarks>
    [InitializeOnLoad]
    public static class CliMenuGenerator
    {
        internal const string GeneratedDirectory = "Assets/UniOpenCLI.Generated";
        internal const string MenuFilePath = GeneratedDirectory + "/CliContextMenu.g.cs";
        private const string AssemblyFilePath = GeneratedDirectory + "/UniOpenCLI.Generated.asmdef";

        private const string MenuRoot = "Assets/Open CLI/";
        private const int BasePriority = 2000;

        static CliMenuGenerator()
        {
            // First run after install: bootstrap the menu from current settings.
            if (File.Exists(MenuFilePath))
                return;

            Generate(UniOpenCliSettings.Commands);
            EditorApplication.delayCall += AssetDatabase.Refresh;
        }

        public static void Generate(IReadOnlyList<CliCommand> commands)
        {
            Directory.CreateDirectory(GeneratedDirectory);

            if (!File.Exists(AssemblyFilePath))
                File.WriteAllText(AssemblyFilePath, BuildAssemblyDefinition());

            File.WriteAllText(MenuFilePath, BuildMenuSource(commands));
        }

        private static string BuildMenuSource(IReadOnlyList<CliCommand> commands)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     Generated by UniOpenCLI. Do not edit: this file is rewritten every time");
            sb.AppendLine("//     settings are applied in Preferences > UniOpen CLI.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UniOpenCLI.Editor;");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine();
            sb.AppendLine("namespace UniOpenCLI.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class CliContextMenuItems");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>();

            for (int i = 0; i < commands.Count; i++)
            {
                string itemName = SanitizeMenuName(commands[i].Name, i, usedNames);
                string literal = ToCSharpLiteral(MenuRoot + itemName);

                sb.AppendLine($"        [MenuItem({literal}, false, {BasePriority + i})] private static void Slot{i}() => CliContextMenu.Open({i});");
                sb.AppendLine($"        [MenuItem({literal}, true)] private static bool ValidateSlot{i}() => CliContextMenu.IsEnabled({i});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string BuildAssemblyDefinition()
        {
            return
@"{
    ""name"": ""UniOpenCLI.Generated"",
    ""rootNamespace"": ""UniOpenCLI.Generated"",
    ""references"": [
        ""UniOpenCLI.Editor""
    ],
    ""includePlatforms"": [
        ""Editor""
    ],
    ""autoReferenced"": false
}
";
        }

        private static string SanitizeMenuName(string name, int index, HashSet<string> usedNames)
        {
            if (string.IsNullOrWhiteSpace(name))
                name = $"CLI {index + 1}";

            // "/" in the name would create a nested submenu.
            name = name.Replace('/', '-').Trim();

            string unique = name;
            int suffix = 2;

            while (!usedNames.Add(unique))
                unique = $"{name} ({suffix++})";

            return unique;
        }

        private static string ToCSharpLiteral(string value)
        {
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }
    }
}
