using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace UniOpenCLI.Editor
{
    [InitializeOnLoad]
    public static class CliMenuGenerator
    {
        private const string GeneratedPath = "Assets/Editor/UniOpenCLI/Generated/CliContextMenuGenerated.cs";

        static CliMenuGenerator()
        {
            if (File.Exists(GeneratedPath))
                return;

            Generate(CliCommandConfig.Load());
            EditorApplication.delayCall += AssetDatabase.Refresh;
        }

        public static void Generate(List<CliCommandData> commands)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by CliMenuGenerator. Do not edit — regenerated on save in Tools/UniOpenCLI.");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine();
            sb.AppendLine("namespace UniOpenCLI.Editor");
            sb.AppendLine("{");
            sb.AppendLine("    public static class CliContextMenuGenerated");
            sb.AppendLine("    {");

            var usedNames = new HashSet<string>();

            for (int i = 0; i < commands.Count; i++)
            {
                string itemName = SanitizeMenuName(commands[i].Name, i, usedNames);
                string literal = ToCSharpLiteral("Assets/Open CLI/" + itemName);

                sb.AppendLine($"        [MenuItem({literal}, false, {2000 + i})] private static void Slot{i}() => CliContextMenu.Open({i});");
                sb.AppendLine($"        [MenuItem({literal}, true)] private static bool ValidateSlot{i}() => CliContextMenu.IsEnabled({i});");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            Directory.CreateDirectory(Path.GetDirectoryName(GeneratedPath));
            File.WriteAllText(GeneratedPath, sb.ToString());
        }

        private static string SanitizeMenuName(string name, int index, HashSet<string> usedNames)
        {
            if (string.IsNullOrWhiteSpace(name))
                name = $"CLI {index + 1}";

            // "/" в имени создал бы вложенное подменю
            name = name.Replace('/', '-').Trim();

            string unique = name;
            int suffix = 2;

            while (!usedNames.Add(unique))
                unique = $"{name} ({suffix++})";

            return unique;
        }

        private static string ToCSharpLiteral(string value)
        {
            return "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
        }
    }
}
